"""Exit classes from Unified Implementation Blueprint §3.13 / §9.16.4."""

from __future__ import annotations

from enum import IntEnum


class ExitClass(IntEnum):
    SUCCESS = 0
    INVALID_USAGE_OR_CONFIG = 2
    APPROVAL_UNAVAILABLE = 3
    POLICY_DENIED = 4
    VERIFICATION_FAILED = 5
    UNVERIFIABLE_INCONCLUSIVE = 6
    PERSISTENCE_CORRUPTION = 7
    INTEGRATION_CONFLICT = 8
    INTERRUPTED = 9
    UNSUPPORTED_CAPABILITY = 10
    EXTERNAL_FAILURE = 11
    INTERNAL_FAILURE = 12


class CommandStatus:
    SUCCESS = "SUCCESS"
    INVALID = "INVALID"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    POLICY_DENIED = "POLICY_DENIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"
    CORRUPT = "CORRUPT"
    INTEGRATION_CONFLICT = "INTEGRATION_CONFLICT"
    INTERRUPTED = "INTERRUPTED"
    UNSUPPORTED = "UNSUPPORTED"
    EXTERNAL_FAILURE = "EXTERNAL_FAILURE"
    INTERNAL_FAILURE = "INTERNAL_FAILURE"
