PRAGMA foreign_keys=ON;
PRAGMA journal_mode=WAL;
PRAGMA synchronous=FULL;
PRAGMA busy_timeout=5000;
CREATE TABLE IF NOT EXISTS schema_meta(schema_version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL, migration_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS schema_migrations(migration_id TEXT PRIMARY KEY, schema_version INTEGER NOT NULL, source_digest TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS goals(goal_id TEXT PRIMARY KEY, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS runs(run_id TEXT PRIMARY KEY, state TEXT NOT NULL, run_version INTEGER NOT NULL, goal_revision_id TEXT, change_revision_id TEXT, repository_snapshot_digest TEXT, candidate_snapshot_digest TEXT, config_digest TEXT, policy_digest TEXT, resume_target_state TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS goal_revisions(goal_revision_id TEXT PRIMARY KEY, goal_id TEXT NOT NULL REFERENCES goals(goal_id), parent_revision_id TEXT, canonical_json TEXT NOT NULL, digest TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS changes(change_id TEXT PRIMARY KEY, goal_id TEXT REFERENCES goals(goal_id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS change_revisions(change_revision_id TEXT PRIMARY KEY, change_id TEXT NOT NULL REFERENCES changes(change_id), goal_revision_id TEXT REFERENCES goal_revisions(goal_revision_id), parent_revision_id TEXT, canonical_json TEXT NOT NULL, digest TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS verification_plans(plan_id TEXT PRIMARY KEY, change_revision_id TEXT REFERENCES change_revisions(change_revision_id), canonical_json TEXT NOT NULL, digest TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS verification_results(check_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), candidate_snapshot_digest TEXT NOT NULL, status TEXT NOT NULL, canonical_json TEXT NOT NULL, digest TEXT NOT NULL UNIQUE, valid INTEGER NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS evidence_manifests(manifest_id TEXT PRIMARY KEY, run_id TEXT REFERENCES runs(run_id), canonical_json TEXT NOT NULL, digest TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS approval_requests(approval_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), request_digest TEXT NOT NULL, disposition TEXT NOT NULL, canonical_json TEXT NOT NULL, consumed_count INTEGER NOT NULL DEFAULT 0, revoked_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS approval_grants(grant_id TEXT PRIMARY KEY, approval_id TEXT NOT NULL REFERENCES approval_requests(approval_id), canonical_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS approval_consumptions(consumption_id INTEGER PRIMARY KEY AUTOINCREMENT, approval_id TEXT NOT NULL REFERENCES approval_requests(approval_id), txn_id TEXT NOT NULL, consumed_at TEXT NOT NULL, UNIQUE(approval_id,txn_id));
CREATE TABLE IF NOT EXISTS events(event_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), sequence INTEGER NOT NULL, event_type TEXT NOT NULL, event_version INTEGER NOT NULL, occurred_at TEXT NOT NULL, canonical_json TEXT NOT NULL, payload_digest TEXT NOT NULL, UNIQUE(run_id,sequence));
CREATE TABLE IF NOT EXISTS artifacts(artifact_digest TEXT PRIMARY KEY, media_type TEXT NOT NULL, byte_length INTEGER NOT NULL, storage_relpath TEXT NOT NULL, classification TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tool_calls(tool_call_id TEXT PRIMARY KEY, run_id TEXT REFERENCES runs(run_id), request_digest TEXT NOT NULL, canonical_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS model_calls(call_id TEXT PRIMARY KEY, run_id TEXT REFERENCES runs(run_id), canonical_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS checkpoints(checkpoint_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), run_version INTEGER NOT NULL, state TEXT NOT NULL, canonical_json TEXT NOT NULL, digest TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS integration_records(integration_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), strategy TEXT NOT NULL, destination_before TEXT NOT NULL, destination_after TEXT, canonical_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS side_effect_txns(txn_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), tool_call_id TEXT NOT NULL, family TEXT NOT NULL, request_digest TEXT NOT NULL, pre_state_digest TEXT, phase TEXT NOT NULL, post_state_digest TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recovery_plans(recovery_plan_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), source_state TEXT NOT NULL, target_state TEXT NOT NULL, canonical_json TEXT NOT NULL, digest TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS locks(lock_name TEXT PRIMARY KEY, owner_id TEXT NOT NULL, acquired_at TEXT NOT NULL, heartbeat_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS events_run_sequence ON events(run_id,sequence);
INSERT OR IGNORE INTO schema_meta(schema_version,applied_at,migration_digest) VALUES(1,datetime('now'),'sha256:phase0f-schema-v1');
INSERT OR IGNORE INTO schema_migrations(migration_id,schema_version,source_digest,applied_at) VALUES('0001_initial',1,'sha256:phase0f-schema-v1',datetime('now'));
